Resources:
  Function:
    Type: AWS::Serverless::Function
    Properties:
      Timeout: 300
      MemorySize: 128
      Handler: aws.Handler
      CodeUri: C:\Users\kropo\IdeaProjects\aws
      Runtime: java21
      Architectures:
        - x86_64